<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY0xez5r\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY0xez5r/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerY0xez5r.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerY0xez5r\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerY0xez5r\appProdProjectContainer([
    'container.build_hash' => 'Y0xez5r',
    'container.build_id' => '3ba42c5f',
    'container.build_time' => 1588218759,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY0xez5r');
